# Configuration for Redmine Issue Notifier Plugin

# Email settings
email:
  # Default CC addresses
  cc: "cc@example.com"
  # Subject prefix for notification emails
  subject_prefix: "[Redmine]"

# Scheduling settings
schedule:
  # Time to send notifications
  send_time: "11:00"
  # Maximum number of notifications to send per day
  max_notifications_per_day: 5

# Custom fields
custom_fields:
  # ID of the custom field used to fetch email addresses
  custom_field_id: nil
